apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: jaeger-tracing-cert
  namespace: istio-ingress 
spec:
  commonName: trace.example.id
  dnsNames:
  - trace.example.id
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  renewBefore: 360h0m0s
  secretName: jaeger-tracing-cert

